### ISSUE TITLE
Secrets.swift File

### ISSUE THREAD

**Issue by tnmendes** [conath/TheatricalMovieTrailers#45]
Can you share some dummy secret class just to run this project?

thank you very much :D

**Comment by conath** [comment]
Sorry about that, the missing file contains my API key for the AppTelemetry backend. That’s why it’s not included.

To run this project, simply delete the file reference from the Xcode project navigator and then rebuild. It will fail once again because of [an analytics-related line in AppDelegate][https://github.com/conath/TheatricalMovieTrailers/blob/84e00acedbb7b5dc32f8cd1e41391f3983ac1ff8/TheatricalMovieTrailers/AppDelegate.swift#L21). You can then comment or delete that and the related lines and it will build.

Note that the app might crash if you keep the other AppTelemetry-related code active, but don’t keep the setup code in AppDelegate. You would have to comment all offending lines, as unfortunately there isn’t a centralised place where you can disable the telemetry.

edit: Note to self: I should update the README to mention the missing file, or find a way to include it without the key and disable the Telemetry in a central place.

**Comment by tnmendes** [comment]
yeah I was already able to run the project...thanks
